"""
Django settings for password_manager project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(hs7j2540#^!h7=dfa&s#n2^*)(fv)2nvz6z@krnwg-3=ldt(l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'manager', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'password_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'password_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # 1 hora

# En tu archivo settings.py

# --- CONFIGURACIÓN DE CORREO ELECTRÓNICO ---
# Es una buena práctica usar variables de entorno para las credenciales,
# pero para depurar, puedes ponerlas directamente aquí (¡no las subas a GitHub!).

# El backend que Django usará para enviar correos. SMTP es el estándar.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Servidor SMTP de tu proveedor de correo.
# Para Gmail: smtp.gmail.com
# Para Outlook/Hotmail: smtp-mail.outlook.com
EMAIL_HOST = 'smtp.gmail.com' 

# Puerto para el servidor. 587 es el estándar para TLS.
EMAIL_PORT = 587

# Usa TLS (seguridad). Debe ser True para la mayoría de los proveedores modernos.
EMAIL_USE_TLS = True

# Tu dirección de correo electrónico completa.
EMAIL_HOST_USER = 'jennifer.ss2004.cuentatrabajo@gmail.com' 

# ¡LA CLAVE! No es tu contraseña normal.
# Debes generar una "Contraseña de Aplicación" en tu cuenta de Google.
EMAIL_HOST_PASSWORD = 'dwhf kmak ypcc gnue' 

# La dirección desde la que se enviarán los correos.
DEFAULT_FROM_EMAIL = 'jennifer.ss2004.cuentatrabajo@gmail.com' 